spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:product-test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console